networks:
  voting-app-nw:
    driver: bridge
services:

  db:
    image: postgres:14.22
    ports:
      - 3306:3306
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    networks:
      - voting-app-nw
    depends_on:
      - worker-app

  redis:
    image: redis
    environment:
      - SKIP_FIX_PERMS=1
    networks:
      - voting-app-nw
    depends_on:
      - voting-app      

  voting-app:
    image: vote:v2
    build:
      context: ./vote/
      dockerfile: Dockerfile
    ports:
      - 5000:80
    networks:
      - voting-app-nw

  result-app:
    image: result:v4
    build:
      context: ./result/
      dockerfile: Dockerfile
    ports:
      - 5001:4000
    networks:
      - voting-app-nw
    depends_on:
      - db

  worker-app:
    image: worker:v2
    build:
      context: ./worker/
      dockerfile: Dockerfile
    networks:
      - voting-app-nw
    depends_on:
      - redis
      